In [2]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.insert(0,'..') # Change this based on your system

import src.Valiant.neuroidal as nm

In [28]:
'''
Use: 
 for N=100, D = 64, K=16, R = 16
1.5 for N=500, D = 128, K= 16, R = 40
1.58 for N=500, D = 256, K = 16, R = 20
1.65 for N=1000 , D = 512, K = 16, R = 20
1.74 for N=2000
1.85 for N=10000
1.9/1.95 for N=100000
1.9/1.95 for N=1000000
2.0 for bigger N
'''

'''
STOP => T
F => k
r_exp => r
N => N
'''

model = nm.NeuroidalModel(N=500,D=128,T=1,k=16,k_adj=1.5,H=10,STOP=0.1,START_MEM=100,r_exp=40,F = 2)
model.create_graph()
model.generate_memory_bank()
model.visualize()
# model.simulate()
# model._generate_adj_mat()
# model.memory_bank

Number of all possible edges: 249500


In [18]:
import colorsys
import numpy as np

def generate_distinct_colors(num_colors):
    colors = []
    for i in range(num_colors):
        hue = i / float(num_colors)
        rgb = colorsys.hsv_to_rgb(hue, 1.0, 1.0)
        colors.append(np.array(rgb))
    return colors

num_colors = 10  # Change this to the number of distinct colors you need
distinct_colors = generate_distinct_colors(num_colors)

distinct_colors

[array([1., 0., 0.]),
 array([1. , 0.6, 0. ]),
 array([0.8, 1. , 0. ]),
 array([0.2, 1. , 0. ]),
 array([0. , 1. , 0.4]),
 array([0., 1., 1.]),
 array([0. , 0.4, 1. ]),
 array([0.2, 0. , 1. ]),
 array([0.8, 0. , 1. ]),
 array([1. , 0. , 0.6])]